run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - govet
    - misspell
    - ineffassign
    - typecheck
    - whitespace
    - gocyclo
    - revive
    - unused

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true
